//
//  XMPPStrings.h
//  NGT International B.V.
//
//  Created by Joost de Moel on 10/12/12.
//  Copyright (c) 2012 NGT International B.V. All rights reserved.
//

#define kValueSessionTerminate         @"session-terminate"
#define kValueSessionAccept            @"session-accept"

#define kAttributeCountryCode          @"countrycode"
#define kAttributeCountryName          @"countryname"

#define kTagNameIq                     @"iq"
#define kTagNameConnection             @"connection"
#define kTagNameChannel                @"channel"
#define kTagNamePresence               @"presence"
#define kTagNameQuery                  @"query"
#define kTagNameX                      @"x"
#define kTagNameDelay                  @"delay"
#define kTagNameField                  @"field"
#define kTagNameValue                  @"value"
#define kTagNameRp                     @"rp"
#define kTagNameInitiator              @"initiator"
#define kTagNameRecipient              @"recipient"
#define kTagNameValidate               @"validate"
#define kTagNameC                      @"c"
#define kTagNameP                      @"p"
#define kTagNameN                      @"n"
#define kTagNameCorrect                @"correct"
#define kTagNameOpen                   @"open"
#define kTagNameClose                  @"close"
#define kTagNameData                   @"data"
#define kTagNameSi                     @"si"
#define kTagNameFile                   @"file"
#define kTagNameFeature                @"feature"
#define kTagNameOption                 @"option"
#define kTagNameDesc                   @"desc"
#define kTagNameAvatar                 @"avatar"
#define kTagNameError                  @"error"
#define kTagNameInternalServerError    @"internal-server-error"
#define kTagNameNotAllowed             @"not-allowed"
#define kTagNameGeoloc                 @"location"
#define kTagNameIgnored                @"ignored"
#define kTagNameInfo                   @"info"
#define kTagNameLat                    @"lat"
#define kTagNameLon                    @"lon"
#define kTagNameList                   @"list"
#define kTagNameName                   @"name"
#define kTagNameOS                     @"os"
#define kTagNameDelete                 @"delete"
#define kTagNameDeleteAll              @"deleteall"
#define kTagNameType                   @"type"
#define kTagNameGet                    @"get"
#define kTagNameForward                @"forward"
#define kTagNameTo                     @"to"
#define kTagNameGetFile                @"getfile"
#define kTagNameAddresses              @"addresses"
#define kTagNameAddress                @"address"
#define kTagNameItemNotFound           @"item-not-found"
#define kTagNameForbidden              @"forbidden"
#define kTagNameBadRequest             @"bad-request"
#define kTagNameToken                  @"token"
#define kTagNameItem                   @"item"
#define kTagNameGroup                  @"group"
#define kTagNameStrength               @"strength"
#define kTagNameStunRtt                @"stunrtt"
#define kTagNameStunTries              @"stuntries"
#define kTagNameProperty               @"property"
#define kTagNameMessage                @"message"
#define kTagNameMute                   @"mute"
#define kTagNameMuted                  @"muted"
#define kTagNameBody                   @"body"
#define kTagNameThread                 @"thread"
#define kTagNameInvite                 @"invite"
#define kTagNameRemoved                @"removed"
#define kTagNameUpdate                 @"update"
#define kTagNameX                      @"x"
#define kTagNameNotification           @"notification"
#define kTagNameNotifications          @"notifications"
#define kTagNameNCC                    @"ncc"
#define kTagNameRequest                @"request"
#define kTagNameVersion                @"version"
#define kTagNameBranch                 @"branch"
#define kTagNameMajor                  @"major"
#define kTagNameMinor                  @"minor"
#define kTagNamePhoneNumber            @"phoneNumber"
#define kTagNameCategory               @"category"
#define kTagNameShow                   @"show"
#define kTagNameSubject                @"subject"
#define kTagNamePriority               @"priority"
#define kTagNameStatus                 @"status"
#define kTagNameNick                   @"nick"
#define kTagNameActive                 @"active"
#define kTagNameFetch                  @"fetch"
#define kTagNameOffline                @"offline"
#define kTagNameFetch                  @"fetch"
#define kTagNameTotal                  @"total"
#define kTagNameSent                   @"sent"
#define kTagNameUsername               @"username"
#define kTagNamePassword               @"password"
#define kTagNameAddresses              @"addresses"
#define kTagNameAddress                @"address"
#define kTagNameMedia                  @"media"
#define kTagNamePermissions            @"permissions"
#define kTagNameAudio                  @"audio"
#define kTagNameAllowed                @"allowed"
#define kTagNameAvailable              @"available"
#define kTagNameAdmin                  @"admin"
#define kTagNamePicture                @"picture"
#define kTagNameRemove                 @"remove"
#define kTagNameGroupChat              @"groupchat"
#define kTagNameGroupChats             @"groupchats"

#define kAttributeDefault              @"default"
#define kAttributeLang                 @"lang"
#define kAttributeLanguage             @"language"
#define kAttributeSWidth               @"swidth"
#define kAttributeSHeight              @"sheight"
#define kAttributeLastset              @"lastset"
#define kAttributeLastcont             @"lastcont"
#define kAttributeBranch               @"branch"
#define kAttributeBrand                @"brand"
#define kAttributeModel                @"model"
#define kAttributeOS                   @"os"
#define kAttributeUserAgent            @"http_user_agent_header"
#define kTagNameStreamStream           @"stream:stream"
#define kTagNameBind                   @"bind"
#define kTagNameSession                @"session"
#define kTagNameResource               @"resource"
#define kTagNameTime                   @"time"
#define kTagNameUploadURL              @"uploadurl"
#define kTagNameEntry                  @"entry"
#define kTagNameFirst                  @"first"
#define kTagNameFirstName              @"firstname"
#define kTagNameLast                   @"last"
#define kTagNameLastName               @"lastname"
#define kTagNameLookup                 @"lookup"
#define kTagNameJoin                   @"join"
#define kTagNameNumber                 @"number"
#define kTagNameEmail                  @"email"
#define kTagNameSleep                  @"sleep"
#define kTagNameProfile                @"profile"
#define kTagNameMCC                    @"mcc"
#define kTagNameMNC                    @"mnc"
#define kTagNamePhone                  @"phone"
#define kTagNamePing                   @"ping"
#define kTagNameReceived               @"received"
#define kTagNameReceivedAck            @"received-ack"
#define kTagNameSearch                 @"search"
#define kTagNameServiceLevel           @"servicelevel"
#define kTagNameUcid                   @"ucid"
#define kTagNameCreate                 @"create"
#define kTagNameParticipants           @"participants"
#define kTagNamePicture                @"picture"
#define kTagNameTitle                  @"title"
#define kTagNameLeave                  @"leave"
#define kTagNameAdd                    @"add"

#define kTagNameActive                 @"active"
#define kTagNameInactive               @"inactive"
#define kTagNameComposing              @"composing"
#define kTagNamePaused                 @"paused"
#define kTagNameGone                   @"gone"

#define kGroupNameAll                  @"All"
#define kGroupNameIM                   @"IM"
#define kGroupNamePB                   @"PB"
#define kGroupNameSearch               @"Search"


// XML attributes and values
#define kAttributeId                   @"id"
#define kAttributeType                 @"type"
#define kAttributeTypeShort            @"t"
#define kAttributeFrom                 @"from"
#define kAttributeTo                   @"to"
#define kAttributeName                 @"name"
#define kAttributeMaxWidth             @"max-width"
#define kAttributeMaxHeight            @"max-height"
#define kAttributeNode                 @"node"
#define kAttributeSenders              @"senders"
#define kAttributeCreator              @"creator"
#define kAttributeDisplay              @"display"
#define kAttributeAdmin                @"admin"
#define kAttributeJID                  @"jid"
#define kAttributeSubscription         @"subscription"
#define kAttributeRemaining            @"remaining"
#define kAttributeAsk                  @"ask"
#define kAttributeExt                  @"ext"
#define kAttributeCode                 @"code"
#define kAttributeStamp                @"stamp"
#define kAttributeVar                  @"var"
#define kAttributeXMLNS_STREAM         @"xmlns:stream"
#define kAttributeLabel                @"label"
#define kAttributePhone                @"phone"
#define kAttributeEmail                @"email"
#define kAttributeStatus               @"status"
#define kAttributeResponse             @"response"
#define kAttributeAction               @"action"
#define kAttributeCc                   @"cc"
#define kAttributeSID                  @"sid"
#define kAttributeBlockSize            @"block-size"
#define kAttributeSeq                  @"seq"
#define kAttributeProfile              @"profile"
#define kAttributeSize                 @"size"
#define kAttributeHeight               @"height"
#define kAttributeClear                @"clear"
#define kAttributeWidth                @"width"
#define kAttributeFormat               @"format"
#define kAttributeMD5                  @"md5"
#define kAttributeUri                  @"uri"
#define kAttributeUrl                  @"url"
#define kAttributeValue                @"value"
#define kAttributeVer                  @"ver"
#define kAttributeVersion              @"version"
#define kAttributeEnable               @"enable"
#define kAttributeEnabled              @"enabled"
#define kAttributeNotifiable           @"notifiable"
#define kAttributeInitiator            @"initiator"
#define kAttributeResponder            @"responder"
#define kAttributeResponderUCID        @"responder_ucid"
#define kAttributeTime                 @"time"
#define kAttributeNumber               @"number"
#define kAttributeISO_639_3_Code       @"iso_639_3_code"
#define kAttributeDeviceID             @"did"
#define kAttributeDeviceType           @"dt"
#define kAttributeHash                 @"hash"
#define kAttributePlatform             @"platform"
#define kAttributeSeconds              @"seconds"
#define kAttributeStunrtt              @"stunrtt"
#define kAttributeStuntries            @"stuntries"
#define kAttributeStrength             @"strength"
#define kAttributeCC                   @"cc"
#define kAttributeThumbnail            @"thumbnail"
#define kAttributeExpires              @"expires"
#define kAttributeRoute                @"route"
#define kAttributeJid                  @"jid"
#define kAttributeUcid                 @"ucid"

#define kTypeAltFrom                   @"altFrom"

#define kValueGet                      @"get"
#define kValueSet                      @"set"
#define kValueResult                   @"result"
#define kValueError                    @"error"
#define kValueProbe                    @"probe"
#define kValueSubscribe                @"subscribe"
#define kValueSubscribed               @"subscribed"
#define kValueUnavailable              @"unavailable"
#define kValueUnsubscribe              @"unsubscribe"
#define kValueUnsubscribed             @"unsubscribed"

#define kValueChat                     @"chat"
#define kValueGroupchat                @"groupchat"

#define kUpdateTypeLeave               @"leave"
#define kUpdateTypeTitle               @"title"
#define kUpdateTypePicture             @"picture"
#define kUpdateTypeRemoved             @"removed"
#define kUpdateTypeJoin                @"join"

#define kValueAway                     @"away"
#define kValueDND                      @"dnd"
#define kValueXA                       @"xa"

#define kValueRemove                   @"remove"
#define kValueBoth                     @"both"
#define kValueTo                       @"to"
#define kValueFrom                     @"from"
#define kValueNone                     @"none"
#define kValueVoiceV1                  @"voice-v1"
#define kValueJingleV1                 @"jingle-v1"
#define kValueJingleV2                 @"jingle-v2"
#define kValueVideoV1                  @"video-v1"
#define kValueVideoChatV1              @"videochat-v1"
#define kValueUcidCaps                 @"ucid:caps"
#define kValueDiscoInfoURL             @"http://jabber.org/protocol/disco#info"
#define kValueSiURL                    @"http://jabber.org/protocol/si"
#define kValueSiFileTransferURL        @"http://jabber.org/protocol/si/profile/file-transfer"
#define kValueFeatureNegURL            @"http://jabber.org/protocol/feature-neg"
#define kValueProtocolGeoloc           @"http://jabber.org/protocol/geoloc"
#define kValueNickProtocol             @"http://jabber.org/protocol/nick"
#define kValueCapabilitiesProtocol     @"http://jabber.org/protocol/caps"
#define kValueStreams                  @"http://etherx.jabber.org/streams"
#define kValueProtocolProfileURL       @"http://jabber.org/protocol/profile"
#define kValueProtocolOffline          @"http://jabber.org/protocol/offline"
#define kValueProtocolSearch           @"http://jabber.org/protocol/rsm"
#define kValueProtocolAddress          @"http://jabber.org/protocol/address"


#define kValueJabberClient             @"jabber:client"
#define kValueJabberIqAuth             @"jabber:iq:auth"
#define kValueJabberIqLast             @"jabber:iq:last"
#define kValueJabberIqRegister         @"jabber:iq:register"
#define kValueJabberIqPrivacy          @"jabber:iq:privacy"
#define kValueJabberVersion            @"jabber:iq:version"
#define kValueXData                    @"jabber:x:data"

#define kValueBindBlock                @"urn:ietf:params:xml:ns:xmpp-bind"
#define kValueSessionBlock             @"urn:ietf:params:xml:ns:xmpp-session"
#define kValueJingle                   @"urn:xmpp:jingle:1"
#define kValueJingleNodes              @"http://jabber.org/protocol/jinglenodes#channel"
#define kValueDiscoItems               @"http://jabber.org/protocol/disco#items"
#define kValueXMPPStanzas              @"urn:ietf:params:xml:ns:xmpp-stanzas"

#define kValueNimbuzzAvatar            @"nimbuzz:avatar"
#define kValueMajor                    @"major"
#define kValueMinor                    @"minor"
#define kValueBuild                    @"build"
#define kValueLanguage                 @"language"
#define kValueLanguageEnUS             @"en-us"
#define kValueLanguageEn               @"en"
#define kValueAvatarServer             @"avatar"
#define kValueSafServer                @"saf"
#define kValueForm                     @"form"
#define kValueStreamMethod             @"stream-method"
#define kValueListSingle               @"list-single"
#define kValueSubmit                   @"submit"
#define kValueSearchServer             @"search"
//#define kValueLocation                 @"gps-v1"
//#define kValueNotifiable               @"notifiable-on"
//#define kValueNotNotifiable            @"notifiable-off"
//#define kValueConnectedViaWiFi         @"conn-wifi"
//#define kValueConnectionType           @"ctype-v1"
//#define kValueConnectedViaCarrier      @"conn-carrier"

// Client Capabilities
#define kCapabilityVoiceCS             @"voice-cs"
#define kCapabilityVoiceIP             @"voice-voip"
#define kCapabilityVideo               @"video"
#define kCapabilityGroupChatV1         @"groupchat-v1"
#define kCapabilityVideoIM             @"video-im"
#define kCapabilityIMAck               @"im-ack"
#define kCapabilityLiveChat            @"livechat-v1"

#define kValueIPHONE                   @"IPHONE"
#define kValueApple                    @"Apple"

#define kValueAccept                   @"accept"
#define kValueCancel                   @"cancel"
#define kValueAdd                      @"add"
#define kValueWait                     @"wait"
#define kValueModify                   @"modify"
#define kValueAuth                     @"auth"

#define kValueFalse                    @"false"
#define kValueTrue                     @"true"

#define kValueXMPPStanzasNS            @"urn:ietf:params:xml:ns:xmpp-stanzas"

#define kServerJingle                  @"jingle"
#define kServerSIP                     @"sip"
#define kServerNout                    @"nout"

#define kValueVoiceMessage             @"voicemessage"
#define kValueAudio                    @"audio"
#define kValueImage                    @"image"
#define kValueVideo                    @"video"
#define kValueAPNS                     @"apns"
#define kValueAPNSPre                  @"apns_pre"
#define kValueAPNSVoip                 @"apns_voip"
#define kValueAPNSVoipPre              @"apns_voip_pre"
#define kValueProtocolFileStore        @"ucid:filestore"
#define kValueUcidPNS                  @"ucid:pns"
#define kValueUcidSearch               @"ucid:search"

#define kNameSpaceUcidMediaShare       @"ucid:mediashare"
#define kXmppNamespaceUcidGroupChat    @"ucid:groupchat"
#define kXmppNamespaceUcidHint         @"ucid:hint"

#define kValueTwoLetterIsoCountryCodeType   @"1"
#define kValueCountryDialingCodeType        @"0"
#define kValueMobileCountryCodeType         @"2"

#define kValueUrnXmppReceipts            @"urn:xmpp:receipts"

#define kValueKilled                     @"killed"


#define kValueEncryption               @"encryption"
#define kValueCrypto                   @"crypto"
#define kAttributeCryptoSuite          @"crypto-suite"
#define kAttributeKeyParams            @"key-params"
#define kAttributeRequired             @"required"

#define kConCheckServer               @"concheck.%@:%d"
#define kXmppGroupChatServer          @"groupchat"
#define kXmppAvatarServer             @"avatar"
